# Configuration for Travis-CI continuous integration.
#
# Copyright 2015, 2018-2020 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: GPL-1.0-or-later OR Artistic-1.0-Perl

language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"

# Only run the exhaustive tests with heavy dependencies on the latest Perl
# version.  (These conditionals are written weirdly backwards so that the
# command line evaluates to true.)
#
# Don't fail the test if Test::MinimumVersion or Test::Perl::Critic cannot
# be installed, since this seems to fail very regularly on Travis-CI.

env: AUTHOR_TESTING=1
before_install:
  - cpanm HTTP::Message
  - cpanm JSON::PP
  - cpanm LWP::UserAgent
  - cpanm Module::Build
  - cpanm Perl6::Slurp
  - cpanm Sub::Install
  - cpanm URI::Escape
  - test "$TRAVIS_PERL_VERSION" != "5.30" || cpanm Perl::Critic         || true
  - test "$TRAVIS_PERL_VERSION" != "5.30" || cpanm Test::MinimumVersion || true
  - test "$TRAVIS_PERL_VERSION" != "5.30" || cpanm Test::Perl::Critic   || true
  - test "$TRAVIS_PERL_VERSION" != "5.30" || cpanm Test::Pod
  - test "$TRAVIS_PERL_VERSION" != "5.30" || cpanm Test::Pod::Coverage
  - test "$TRAVIS_PERL_VERSION" != "5.30" || cpanm Test::Strict
  - test "$TRAVIS_PERL_VERSION" != "5.30" || cpanm Test::Synopsis

branches:
  except:
    - /^debian\/.*/
    - pristine-tar
    - /^upstream\/.*/
