language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

# Only run the exhaustive tests with heavy dependencies on the latest Perl
# version.  (These conditionals are written weirdly backwards so that the
# command line evaluates to true.)

env: AUTHOR_TESTING=1
before_install:
  - cpanm HTTP::Message
  - cpanm JSON::PP
  - cpanm LWP::UserAgent
  - cpanm Perl6::Slurp
  - cpanm Sub::Install
  - cpanm URI::Escape
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::MinimumVersion
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::Perl::Critic
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::Pod
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::Pod::Coverage
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::Strict
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::Synopsis

branches:
  except:
    - /^debian\/.*/
    - pristine-tar
    - /^upstream\/.*/
