# Representation of a single Duo phone for the Admin API.
#
# This class wraps the Duo representation of a single Duo phone, as returned
# by (for example) the Admin /phones REST endpoint.

package Net::Duo::Admin::Phone 1.00;

use 5.014;
use strict;
use warnings;

use parent qw(Net::Duo::Object);

use Net::Duo::Admin::User;

# Data specification for converting JSON into our object representation.  See
# the Net::Duo::Object documentation for syntax information.
## no critic (Subroutines::ProhibitUnusedPrivateSubroutines)
sub _fields {
    return {
        activated          => 'simple',
        capabilities       => 'array',
        extension          => 'simple',
        name               => 'simple',
        number             => 'simple',
        phone_id           => 'simple',
        platform           => 'simple',
        postdelay          => 'simple',
        predelay           => 'simple',
        sms_passcodes_sent => 'simple',
        type               => 'simple',
        users              => 'Net::Duo::Admin::User',
    };
}
## use critic

# Install our accessors.
Net::Duo::Admin::Phone->install_accessors;

1;
__END__

=for stopwords
Allbery MERCHANTABILITY NONINFRINGEMENT SMS passcodes sublicense

=head1 NAME

Net::Duo::Admin::Phone - Representation of a Duo phone

=head1 SYNOPSIS

    my $decoded_json = get_json();
    my $phone = Net::Duo::Admin::Phone->new($decoded_json);
    say $phone->number;

=head1 DESCRIPTION

A Net::Duo::Admin::Phone object is a Perl representation of a Duo phone as
returned by the Duo Admin API, usually via the phones() method or nested
in a user returned by the users() method.  It contains various information
about a phone.

=head1 CLASS METHODS

=over 4

=item new(DUO, DATA)

Creates a new Net::Duo::Admin::Phone object from a full data set.  DUO is
the Net::Duo object that should be used for any further actions on this
object.  DATA should be the data structure returned by the Duo REST API
for a single user, after JSON decoding.

=back

=head1 INSTANCE METHODS

=over 4

=item activated()

Whether the phone has been activated for Duo Mobile.

=item capabilities()

A list of phone capabilities, chosen from the following values:

=over 4

=item C<push>

The device is activated for Duo Push.

=item C<phone>

The device can receive phone calls.

=item C<sms>

The device can receive batches of SMS passcodes.

=back

=item extension()

The extension for this phone, if any.

=item name()

The name of this phone.

=item number()

The number for this phone, without any extension.

=item phone_id()

The unique ID of this phone as generated by Duo on phone creation.

=item platform()

The phone for Duo Mobile, or C<unknown> for a generic phone type.  For the
list of valid values, see the Duo Admin API documentation.

=item postdelay()

The time (in seconds) to wait after the extension is dialed and before the
speaking the prompt.

=item predelay()

The time (in seconds) to wait after the number picks up and before dialing
the extension.

=item sms_passcodes_sent()

Whether SMS passcodes have been sent to this phone.

=item type()

The type of phone, chosen from C<unknown>, C<mobile>, or C<landline>.

=item users()

The users associated with this phone as a list of Net::Duo::Admin::User
objects.

=back

=head1 AUTHOR

Russ Allbery <rra@cpan.org>

=head1 COPYRIGHT AND LICENSE

Copyright 2014 The Board of Trustees of the Leland Stanford Junior
University

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

=head1 SEE ALSO

L<Net::Duo::Admin>

L<Duo Admin API for phones|https://www.duosecurity.com/docs/adminapi#phones>

=cut
